spring.application.name=taller_jwt

#conexion a postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/taller_jwt_bd
spring.datasource.username=postgres
spring.datasource.password=pgadmin4

#Driver
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate crea y actualizar tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

#mostrar sql en consola
spring.jpa.show-sql=true

#formatear sql
spring.jpa.properties.hibernate.format_sql=true

#mostrar parametros sql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect